{% set name = "filter_1col" %}
{% set version = "1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source: 
  path: ../src

requirements:
  host:
    - perl
  run:
    - perl

about:
  home: https://github.com/bidauxpoto/bd-filter_1col
  summary: Bioinformatic and data analysis power tool to filter a table on one column (more efficient and less error prone than grep -f) 
